version: 2

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#buildpack-deps
      # https://hub.docker.com/r/circleci/buildpack-deps/tags/
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - v1-pencil-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "release.nix" }}
      #       - v1-pencil-
      - run:
          name: Install nix
          command: curl https://nixos.org/nix/install | sh
      - run:
          name: Run tests using ghc-8.4
          command: nix-shell --attr env release-ghc-8.4.nix --run "cabal new-test"
      - run:
          name: Run tests using ghc-8.2
          command: nix-shell --attr env release-ghc-8.2.nix --run "cabal new-test"
      - run:
          name: Build using nix-build
          command: nix-build --attr env
      # - save_cache:
      #     key: v1-pencil-{{ checksum "elbenshiracom.cabal" }}-{{ checksum "release.nix" }}
      #     paths:
      #       - /nix/
      # - run:
      #     name: Generate website
      #     command: make all
      #     no_output_timeout: 45m
      # - save_cache:
      #     # Save the built files to be deployed later
      #     key: v1-pencil-build-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - out
  # deploy:
  #   docker:
  #     - image: circleci/buildpack-deps:bionic-curl
  #   steps:
  #     - checkout
  #     # - restore_cache:
  #     #     keys:
  #     #       - v1-pencil-build-{{ .Branch }}-{{ .Revision }}
  #     #       - v1-pencil-build
  #     - run:
  #         name: Deploy website
  #         command: make deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
          filters:
            branches:
              only: update-packages-for-nix
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         # Only deploy website files from the `source` branch
      #         only: source
      #
