version: 2

# Also based off: https://github.com/johnae/circleci-nix

references:
  prepare_ci: &prepare_container
    run:
      name: Prepare Container
      command: |
        nix-channel --add \
        https://nixos.org/channels/nixpkgs-unstable nixpkgs && \
        nix-channel --update
        nix-env -iA nixpkgs.haskellPackages.cabal-install
        nix-env -iA nixpkgs.haskellPackages.doctest

jobs:
  build:
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#buildpack-deps
      # https://hub.docker.com/r/circleci/buildpack-deps/tags/
      # - image: circleci/buildpack-deps:bionic-curl

      - image: nixorg/nix:circleci
    steps:
      - checkout

      - *prepare_container

      # - restore_cache:
      #     keys:
      #       - v1-pencil-{{ .Branch }}-{{ .Revision }}
      #       - v1-pencil-{{ .Branch }}-
      #       - v1-pencil-

      # - run:
      #     name: Restore nix cache
      #     command: |
      #       if [ -e /nix-cache/pencil-nix-cache.nar ]; then
      #         echo "/nix-cache/pencil-nix-cache.nar present, importing into store."
      #         nix-store --import < /nix-cache/pencil-nix-cache.nar
      #       else
      #         echo "/nix-cache/pencil-nix-cache.nar missing, skipping store import."
      #       fi

      - run:
          name: Run tests using ghc-8.4
          command: |
            nix-shell --attr env release-ghc-8.4.nix --run "cabal update && cabal new-test"
            # nix-shell --attr env release-ghc-8.4.nix --run "doctest src/"
      - run:
          name: Run tests using ghc-8.2
          command: |
            nix-shell --attr env release-ghc-8.2.nix --run "cabal update && cabal new-test"
            # nix-shell --attr env release-ghc-8.2.nix --run "doctest src/"
      - run:
          name: Build using nix-build
          command: nix-build --attr env

      # - run:
      #     name: Create nix cache
      #     command: |
      #       mkdir -p /nix-cache
      #       nix-store --export $(nix-store -qR the-pencil-build-path) > /nix-cache/pencil-nix-cache.nar
      #       NIXSH

      # - save_cache:
      #     key: v1-pencil-{{ .Branch }}-{{ .Revision }}
      #     paths:
      #       - /nix-cache/pencil-nix-cache.nar
